In [7]:
import torch

In [ ]:
t1=torch.tensor(4.)

In [ ]:
t1 #number

tensor(4.)

In [ ]:
t1.dtype

torch.float32

In [ ]:
t2=torch.tensor([1.,2,3,4]) # same data type 

In [ ]:
t2

tensor([1., 2., 3., 4.])

In [ ]:
# matrix
t3=torch.tensor([[5.6],[7,8],[9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
t4=torch.tensor([
                 [[11,12,13],
                  [13,14,15]],
                 [[15,16,17],
                  [17,18,19.]]])

In [ ]:
t4.shape  

torch.Size([2, 2, 3])

In [ ]:
t1.shape #number

torch.Size([])

In [ ]:
t2.shape # vector

torch.Size([4])

In [ ]:
t3.shape # matrix

torch.Size([3, 2])

In [ ]:
 #create tensor
 x=torch.tensor(3.)
 w=torch.tensor(4.,requires_grad=True)
 b=torch.tensor(5.,requires_grad=True)

In [ ]:
y= w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
y.backward() # compute derivative use for optimization alg(gradient desecent)

In [ ]:
print('dy/dx',x.grad) # requires grad None
print('dy/dw',w.grad)# true
print('dy/db',b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


In [ ]:
x

tensor(3.)

In [3]:
import numpy as np
x=np.array([[1,2],[3,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [ ]:
# convt numpy  to tensor
y=torch.from_numpy(x)

In [ ]:
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [ ]:
# convt tensor to numpy
z=y.numpy()

In [ ]:
z

array([[1., 2.],
       [3., 4.]])

In [1]:
# pytorch use GPU it is fast


In [4]:
# Training data
#input (temp , rain ,humidity)
inputs=np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [5]:
# Target data (apple,oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [8]:
# convt to tensor
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [13]:
# weight and bias
w=torch.randn(2,3,requires_grad=True) # 2,rows 3 columns # matrix
b=torch.randn(2,requires_grad=True) # vector
print(w)
b



tensor([[ 1.7865e+00, -4.0421e-04, -3.8661e-01],
        [ 6.7550e-01,  1.0447e+00,  9.4444e-01]], requires_grad=True)


tensor([-1.2845, -0.6817], requires_grad=True)

In [14]:
def model(x):
  return x @  w.t() +b  # x @(multiple) w.t(weight transpose matrix) b(bias)(vector) 

In [15]:
# prediction
preds = model(inputs)
print(preds)

tensor([[112.4803, 159.2379],
        [136.5105, 213.1695],
        [131.6654, 252.8583],
        [166.6187, 148.0874],
        [ 94.8842, 212.3328]], grad_fn=<AddBackward0>)


In [16]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [17]:
diff =preds  - targets
diff_sqr=diff**2
diff_sqr

tensor([[ 3190.0278,  7963.3945],
        [ 3081.4138, 12581.9922],
        [  160.4133, 14366.0098],
        [20914.5762, 12340.4004],
        [   65.8664,  8711.0186]], grad_fn=<PowBackward0>)

In [20]:
# MSR loss
def mse(t1,t2):
  diff = t1-t2
  return torch.sum(diff**2) / diff.numel()


In [21]:
# compute loss
loss= mse(preds,targets)
loss    # very bad

tensor(8337.5107, grad_fn=<DivBackward0>)

In [29]:
# compute gradient 

loss.backward()

RuntimeError: ignored

In [24]:
print(w)
print(w.grad)

tensor([[ 1.7865e+00, -4.0421e-04, -3.8661e-01],
        [ 6.7550e-01,  1.0447e+00,  9.4444e-01]], requires_grad=True)
tensor([[4893.5063, 3161.1519, 2299.7415],
        [8984.0674, 9129.5137, 5722.2773]])
